Resources:
  MasterResourceTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_RESOURCES_TABLE}
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
        - AttributeName: indexSortKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: GSI_1
          KeySchema:
            - AttributeName: sortKey
              KeyType: HASH
            - AttributeName: indexSortKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  UsersLookupTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_USER_LOOKUP_TABLE}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: UserIdGSI
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  TokenLookupTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TOKEN_LOOKUP_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
